# Only trigger on tags
name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF :11}
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install & configure Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.5.1

      - name: Update poetry package version
        run: poetry version ${{ env.version }}

